nome = input("Informe seu nome: ")
idade = input("Informe sua idade: ")

print(nome, idade)
print(nome, idade, end="...\n")
print(nome , idade, sep="#")
print(nome, idade, sep="#" , end="...\n" )
#nome= ("Daniel")
#sobrenome= ("Valadão")
#print (nome, sobrenome, end="...\n")
#print (nome, sobrenome, sep="#")
